### Load the dataset

In [4]:
# ! pip install datasets

In [5]:
! pip install -U pillow

Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (9.3.0)
Collecting pillow
  Downloading pillow-11.1.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Downloading pillow-11.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 41.8 MB/s eta 0:00:0000:010:01
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.3.0
    Uninstalling Pillow-9.3.0:
      Successfully uninstalled Pillow-9.3.0
Successfully installed pillow-11.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: python -m pip install --upgrade pip

In [1]:
from datasets import load_dataset

dataset = load_dataset("naver-clova-ix/cord-v2")

dataset

DatasetDict({
    train: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 800
    })
    validation: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 100
    })
    test: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 100
    })
})

In [2]:
image = dataset["test"][2]["image"]

image.save("test_image.png")

In [3]:
import json
ground_truth = json.loads(dataset["test"][2]["ground_truth"])

In [4]:
ground_truth["gt_parse"]

{'menu': {'nm': 'JASMINE MT ( L )',
  'cnt': '1',
  'price': '24,000',
  'sub': {'nm': 'COCONUT JELLY ( L )', 'price': '4,000'}},
 'sub_total': {'subtotal_price': '28,000'},
 'total': {'total_price': '28,000',
  'cashprice': '100,000',
  'changeprice': '72,000',
  'menuqty_cnt': '1'}}

In [36]:
! nvidia-smi

Sat Mar  8 18:24:36 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:56:00.0 Off |                    0 |
|  0%   17C    P8             21W /  300W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
! pip install git+https://github.com/huggingface/transformers accelerate

Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-0ugh6ejg
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-0ugh6ejg
  Resolved https://github.com/huggingface/transformers to commit 858545047c05a35fde437b2ada3a901844cd1e60
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting accelerate
  Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (0.29.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (6.0.1)
Collecting regex!=2019.12.17 (from transformers==4.50.0.dev0)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (2.32.3)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.50.0.dev0)
  Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers==4.50.0.dev0)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.6)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.0.1+cu118)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers==4.50.0.dev0) (2024.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers==4.50.0.dev0) (4.4.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=2.0.0->accelerate) (3.25.0)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=2.0.0->accelerate) (15.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2.0.0->accelerate) (1.3.0)
Downloading accelerate-1.4.0-py3-none-any.whl (342 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 13.3 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 74.6 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 126.0 MB/s eta 0:00:00
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 249.2 MB/s eta 0:00:00
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.50.0.dev0-py3-none-any.whl size=10877796 sha256=6993eb994a7230c575d02ac6519b1100c2af1dcaaeea70142ddff9b32cb13373
  Stored in directory: /tmp/pip-ephem-wheel-cache-g3snm2mz/wheels/c0/14/d6/6c9a5582d2ac191ec0a483be151a4495fe1eb2a6706ca49f1b
Successfully built transformers
Installing collected packages: safetensors, regex, tokenizers, transformers, accelerate
Successfully installed accelerate-1.4.0 regex-2024.11.6 safetensors-0.5.3 tokenizers-0.21.0 transformers-4.50.0.dev0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: python -m pip install --upgrade pip

In [4]:
! nvidia-smi

Mon Mar 10 15:52:00 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:52:00.0 Off |                    0 |
|  0%   27C    P8             28W /  300W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [5]:
! pip install git+https://github.com/huggingface/transformers accelerate

Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-v5f5e750
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-v5f5e750
  Resolved https://github.com/huggingface/transformers to commit 858545047c05a35fde437b2ada3a901844cd1e60
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (1.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (0.29.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (1.24.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.50.0.dev0) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.6)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.0.1+cu118)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers==4.50.0.dev0) (2024.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers==4.50.0.dev0) (4.4.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=2.0.0->accelerate) (3.25.0)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=2.0.0->accelerate) (15.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.50.0.dev0) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2.0.0->accelerate) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: python -m pip install --upgrade pip

In [6]:
! pip install qwen-vl-utils[decord]==0.0.8

Collecting qwen-vl-utils==0.0.8 (from qwen-vl-utils[decord]==0.0.8)
  Downloading qwen_vl_utils-0.0.8-py3-none-any.whl.metadata (3.6 kB)
Collecting av (from qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8)
  Downloading av-14.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8) (23.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8) (11.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8) (2.32.3)
Collecting decord (from qwen-vl-utils[decord]==0.0.8)
  Downloading decord-0.6.0-py3-none-manylinux2010_x86_64.whl.metadata (422 bytes)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from decord->qwen-vl-utils[decord]==0.0.8) (1.24.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->qwen-vl-utils==0.0.8->qwen-vl-utils[decord]==0.0.8) (2022.12.7)
Downloading qwen_vl_utils-0.0.8-py3-none-any.whl (5.9 kB)
Downloading av-14.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.8/38.8 MB 117.2 MB/s eta 0:00:0000:0100:01
Downloading decord-0.6.0-py3-none-manylinux2010_x86_64.whl (13.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 249.4 MB/s eta 0:00:00a 0:00:01
Installing collected packages: decord, av, qwen-vl-utils
Successfully installed av-14.2.0 decord-0.6.0 qwen-vl-utils-0.0.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: python -m pip install --upgrade pip

In [7]:
! pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.0.1+cu118)
Collecting torch
  Downloading https://download.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp310-cp310-linux_x86_64.whl.metadata (28 kB)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (0.15.2+cu118)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp310-cp310-linux_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.10/dist-packages (2.0.2+cu118)
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp310-cp310-linux_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.9.0)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2024.12.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 138.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 183.4 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 126.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 18.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 23.7 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 42.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 119.6 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 82.2 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 43.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 62.7 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvtx-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 52.3 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 44.0 MB/s eta 0:00:0000:0100:01
Collecting triton==3.2.0 (from torch)
  Downloading https://download.pytorch.org/whl/triton-3.2.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Collecting sympy==1.13.1 (from torch)
  Downloading https://download.pytorch.org/whl/sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 131.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchvision) (1.24.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.2)
Downloading https://download.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp310-cp310-linux_x86_64.whl (768.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 768.4/768.4 MB 16.9 MB/s eta 0:00:0000:0100:01
Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 72.3 MB/s eta 0:00:0000:0100:01
Downloading https://download.pytorch.org/whl/triton-3.2.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (166.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.6/166.6 MB 68.6 MB/s eta 0:00:0000:0100:01
Downloading https://download.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp310-cp310-linux_x86_64.whl (7.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 245.2 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp310-cp310-linux_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 229.9 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: triton, nvidia-cusparselt-cu12, typing-extensions, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch, torchvision, torchaudio
  Attempting uninstall: triton
    Found existing installation: triton 2.0.0
    Uninstalling triton-2.0.0:
      Successfully uninstalled triton-2.0.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.4.0
    Uninstalling typing_extensions-4.4.0:
      Successfully uninstalled typing_extensions-4.4.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1+cu118
    Uninstalling torch-2.0.1+cu118:
      Successfully uninstalled torch-2.0.1+cu118
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.15.2+cu118
    Uninstalling torchvision-0.15.2+cu118:
      Successfully uninstalled torchvision-0.15.2+cu118
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.0.2+cu118
    Uninstalling torchaudio-2.0.2+cu118:
      Successfully uninstalled torchaudio-2.0.2+cu118
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 sympy-1.13.1 torch-2.6.0+cu124 torchaudio-2.6.0+cu124 torchvision-0.21.0+cu124 triton-3.2.0 typing-extensions-4.12.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 25.0.1
[notice] To update, run: python -m pip install --upgrade pip

### Load the model and processor

In [5]:
from transformers import Qwen2_5_VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2.5-VL-7B-Instruct", torch_dtype="auto", device_map="auto"
)

# default processer
processor = AutoProcessor.from_pretrained("Qwen/Qwen2.5-VL-7B-Instruct")

config.json:   0%|          | 0.00/1.37k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/57.6k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/5 [00:00<?, ?it/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/3.90G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00005-of-00005.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/244 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json:   0%|          | 0.00/7.23k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

In [6]:
! nvidia-smi

Mon Mar 10 15:56:12 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:52:00.0 Off |                    0 |
|  0%   30C    P0             72W /  300W |   16089MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+

### Prompt

In [109]:
schema_dict = {
    "menu":
    {
        "nm": "name of the menu",
        "num": "identification number of menu",
        "unitprice": "unit price of menu",
        "cnt": "quantity of menu",
        "discountprice": "discounted price of menu",
        "price": "total price of menu",
        "itemsubtotal": "price of each menu after discount applied",
        "vatyn": "whether the price includes tax or not",
        "etc": "others",
        "sub": {
            "nm": "name of submenu",
            "unitprice": "unit price of submenu",
            "cnt": "quantity of submenu",
            "price": "total price of submenu",
            "etc": "others"
        }

    },
    "sub_total":
    {
        "price": "subtotal price",
        "discount_price": "discounted price in total",
        "service_price": "service charge",
        "othersvc_price": "added charge other than service charge",
        "tax_price": "tax amount",
        "etc": "others"
    },
    "total":
    {
        "total_price": "total price",
        "etc": "others",
        "cashprice": "amount of price paid in cash",
        "changeprice": "amount of change in cash",
        "creditcardprice": "amount of price paid in credit/debit card",
        "emoneyprice": "amount of price paid in emoney, point",
        "menutype_cnt": "total count of type of menu",
        "menuqty_cnt": "total count of quantity"
    }
}

In [37]:
prompt = (
    "You are a Vision Language Model specialized in extracting structured data from visual representations of palette manifests. "
    + "Your task is to analyze the provided image of a palette manifest and extract the relevant information into a well-structured JSON format. "
    + "The palette manifest includes details such as menu, sub menu, sub total and total. "
    + "Focus on identifying key data fields and ensuring the output adheres to the requested JSON structure. "
    + "Provide only the JSON output based on the extracted information. Avoid additional explanations or comments."
    + f"{schema_dict}"
    + "Fill the keys only if the information is available"
)

prompt

"You are a Vision Language Model specialized in extracting structured data from visual representations of palette manifests. Your task is to analyze the provided image of a palette manifest and extract the relevant information into a well-structured JSON format. The palette manifest includes details such as menu, sub menu, sub total and total. Focus on identifying key data fields and ensuring the output adheres to the requested JSON structure. Provide only the JSON output based on the extracted information. Avoid additional explanations or comments.{'menu': [{'nm': 'name of the menu', 'num': 'identification number of menu', 'unitprice': 'unit price of menu', 'cnt': 'quantity of menu', 'discountprice': 'discounted price of menu', 'price': 'total price of menu', 'itemsubtotal': 'price of each menu after discount applied', 'vatyn': 'whether the price includes tax or not', 'etc': 'others', 'sub': {'nm': 'name of submenu', 'unitprice': 'unit price of submenu', 'cnt': 'quantity of submenu', 'price': 'total price of submenu', 'etc': 'others'}}], 'sub_total': {'price': 'subtotal price', 'discount_price': 'discounted price in total', 'service_price': 'service charge', 'othersvc_price': 'added charge other than service charge', 'tax_price': 'tax amount', 'etc': 'others'}, 'total': {'total_price': 'total price', 'etc': 'others', 'cashprice': 'amount of price paid in cash', 'changeprice': 'amount of change in cash', 'creditcardprice': 'amount of price paid in credit/debit card', 'emoneyprice': 'amount of price paid in emoney, point', 'menutype_cnt': 'total count of type of menu', 'menuqty_cnt': 'total count of quantity'}}Fill the keys only if the information is available"

In [38]:
def create_messages(image_path, prompt):
    messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": image_path,
                "resized_height": 640,
                "resized_width": 640
            },
            {"type": "text", "text": prompt},
        ],
    }
]
    return messages

In [39]:
def infer(messages, model, processor):
    # Preparation for inference
    text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )
    inputs = inputs.to("cuda")
    
    # Inference: Generation of the output
    generated_ids = model.generate(**inputs, max_new_tokens=2048)
    generated_ids_trimmed = [
        out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]
    output_text = processor.batch_decode(
        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )
    return output_text

In [40]:
import os

if not os.path.exists("tests"):
    os.mkdir("tests")

In [72]:
import json
from tqdm import tqdm

i = 0
prediction_list = []
ground_truth_list = []

for row in tqdm(dataset["test"]):
    image = row["image"]
    image_path = os.path.join("tests", f"test_{i}.png")
    image.save(image_path)

    ground_truth = json.loads(row["ground_truth"])["gt_parse"]
    ground_truth_list.append(ground_truth)

    messages = create_messages(image_path=image_path, prompt=prompt)

    prediction = infer(messages=messages, model=model, processor=processor)
    prediction_list.append(prediction)
    i += 1

100%|██████████| 100/100 [22:22<00:00, 13.42s/it]

In [73]:
def postprocess(text):
    parsed_text = ""
    try:
        parsed_text = json.loads(text[0].replace("```json", "").replace("```", ""))
        return parsed_text
    except:
        raise ValueError(f"Unable to parse prediction text - {text}")

In [74]:
prediction_list = [postprocess(x) for x in prediction_list]

In [77]:
ground_truth_list[1]

{'menu': [{'nm': 'J.STB PROMO', 'price': '17500'},
  {'nm': 'Y.B.BAT', 'price': '46000'},
  {'nm': 'Y.BASO PROM', 'price': '27500'}],
 'total': {'total_price': '91000', 'cashprice': '91000'}}

In [61]:
from collections import Counter

def flatten_dict(d, parent_key=""):
    items = {}
    for k, v in d.items():
        new_key = f"{parent_key}.{k}" if parent_key else k
        
        if isinstance(v, dict):  
            items.update(flatten_dict(v, new_key))
            
        elif isinstance(v, list):  
            if all(isinstance(i, dict) for i in v):
                for idx, item in enumerate(v):
                    items.update(flatten_dict(item, f"{new_key}[{idx}]"))
            else:
                items[new_key] = v
        else:
            items[new_key] = v

    return items

In [78]:
ground_truth_list[1]

{'menu': [{'nm': 'J.STB PROMO', 'price': '17500'},
  {'nm': 'Y.B.BAT', 'price': '46000'},
  {'nm': 'Y.BASO PROM', 'price': '27500'}],
 'total': {'total_price': '91000', 'cashprice': '91000'}}

In [111]:
metrics_list = []
for i in range(len(prediction_list)):
    
    metrics_dict = {}
    gt = ground_truth_list[i]
    pred = prediction_list[i]

    if isinstance(gt["menu"], dict):
      gt["menu"] = [gt["menu"]]
    if isinstance(pred["menu"], dict):
      pred["menu"] = [pred["menu"]]
    
    gt_flat = flatten_dict(gt)
    pred_flat = flatten_dict(pred)

    total_keys = len(gt_flat)
    matched_keys = 0
    
    for key, gt_value in gt_flat.items():
        pred_value = pred_flat.get(key, "")
        if gt_value == pred_value:
            matched_keys += 1

    metrics_dict["invoice_no"] = i
    metrics_dict["total_keys"] = total_keys
    metrics_dict["matched_keys"] = matched_keys
    metrics_dict["accuracy"] = (matched_keys / total_keys ) * 100
    metrics_list.append(metrics_dict)

In [112]:
import pandas as pd

metrics_df = pd.DataFrame(metrics_list)

metrics_df.round(2)

    invoice_no  total_keys  matched_keys  accuracy
0            0          11             9     81.82
1            1           8             8    100.00
2            2          10             2     20.00
3            3           8             5     62.50
4            4          14            10     71.43
..         ...         ...           ...       ...
95          95          12            10     83.33
96          96          11            10     90.91
97          97          13             7     53.85
98          98          13             5     38.46
99          99          29            13     44.83

[100 rows x 4 columns]

In [113]:
metrics_df["accuracy"].mean()

68.07570195167807

In [141]:
def extract_values(data, level, key):
    values = []
    if level == "sub" and isinstance(data, dict) and "sub" in data["menu"]:
      menu = data["menu"]
    else:
      menu = data.get(level, [])
    if isinstance(menu, dict):
        if key in menu:
            values.append(menu[key])
    else:
        for item in menu:
            if key in item:
                values.append(item[key])

    return values

In [142]:
prediction_list[1]

{'menu': [{'nm': 'J.STB PROMO',
   'unitprice': '17500',
   'cnt': '1',
   'discountprice': '17500',
   'price': '17500',
   'itemsubtotal': '17500',
   'vatyn': '',
   'etc': ''},
  {'nm': 'Y.B.BAT',
   'unitprice': '46000',
   'cnt': '1',
   'discountprice': '46000',
   'price': '46000',
   'itemsubtotal': '46000',
   'vatyn': '',
   'etc': ''},
  {'nm': 'Y.BASO PROM',
   'unitprice': '27500',
   'cnt': '1',
   'discountprice': '27500',
   'price': '27500',
   'itemsubtotal': '27500',
   'vatyn': '',
   'etc': ''}],
 'sub_total': {'price': '91000',
  'discount_price': '91000',
  'service_price': '',
  'othersvc_price': '',
  'tax_price': '',
  'etc': ''},
 'total': {'total_price': '91000',
  'cashprice': '91000',
  'changeprice': '',
  'creditcardprice': '',
  'emoneyprice': '',
  'menutype_cnt': '3',
  'menuqty_cnt': '3'}}

In [143]:
extract_values(data=prediction_list[0], level="menu", key="nm")

['-TICKET CP']

In [148]:
keys_to_evaluate = []

keys = ["menu", "sub", "sub_total", "total"]

for k in keys:
    if k == "sub":
        d = schema_dict["menu"][k]
    else:
        d = schema_dict[k]

    for k1 in d.keys():
        keys_to_evaluate.append(f"{k}.{k1}")

print(keys_to_evaluate)

['menu.nm', 'menu.num', 'menu.unitprice', 'menu.cnt', 'menu.discountprice', 'menu.price', 'menu.itemsubtotal', 'menu.vatyn', 'menu.etc', 'menu.sub', 'sub.nm', 'sub.unitprice', 'sub.cnt', 'sub.price', 'sub.etc', 'sub_total.price', 'sub_total.discount_price', 'sub_total.service_price', 'sub_total.othersvc_price', 'sub_total.tax_price', 'sub_total.etc', 'total.total_price', 'total.etc', 'total.cashprice', 'total.changeprice', 'total.creditcardprice', 'total.emoneyprice', 'total.menutype_cnt', 'total.menuqty_cnt']

In [163]:
from collections import Counter


def compute_metrics(gt_values, pred_values):
    """Computes Precision, Recall, F1-score, and Accuracy for exact matches."""

    gt_counter = Counter(gt_values)
    pred_counter = Counter(pred_values)

    tp = 0  # True Positives (Correct Matches)
    fp = 0  # False Positives (Extra Predictions)
    fn = 0  # False Negatives (Missing Predictions)

    matched_pred = set()

    # Exact Matches
    for val in gt_counter:
        if val in pred_counter:
            tp += min(gt_counter[val], pred_counter[val])  # Count matches
            matched_pred.add(val)

    # Compute FP (Extra Predictions not in GT)
    fp = sum(pred_counter[val] for val in pred_counter if val not in matched_pred)

    # Compute FN (Missing Predictions in GT)
    fn = sum(gt_counter[val] for val in gt_counter if val not in matched_pred)

    return {"tp": tp, "fp": fp, "fn": fn}

In [183]:
i = 0

metrics = {key: {"tp": 0, "fp": 0, "fn": 0, "total_gt": 0} for key in keys_to_evaluate}
for gt, pred in zip(ground_truth_list, prediction_list):
    for key in keys_to_evaluate:
        level, sub_level = key.split('.')
        gt_values = extract_values(data=gt, level=level, key=sub_level)
        pred_values = extract_values(data=pred, level=level, key=sub_level)
        # print(key, gt_values, pred_values)

        gt_values = [str(x) for x in gt_values]
        pred_values = [str(x) for x in pred_values]

        # compute the precision, recall and f1-score for the key    
        instance_metrics = compute_metrics(gt_values, pred_values)
        # print(key, instance_metrics)

        metrics[key]["tp"] += instance_metrics["tp"]
        metrics[key]["fp"] += instance_metrics["fp"]
        metrics[key]["fn"] += instance_metrics["fn"]
        metrics[key]["total_gt"] += len(gt_values)

In [194]:
final_metrics = []

for key, value in metrics.items():
    tp, fp, fn, total_gt = value["tp"], value["fp"], value["fn"], value["total_gt"]

    # precision
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0

    # Recall
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0

    # F1-score
    f1_score = ( 2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    # Accuracy
    accuracy = tp / total_gt if total_gt > 0 else 0

    final_metrics.append({
        "key" : key,
        "precision" : precision,
        "recall" : recall,
        "f1-score" : f1_score,
        "tp" : tp,
        "total_gt": total_gt,
        "accuracy" : accuracy
    })

In [195]:
final_metrics_df = pd.DataFrame(final_metrics)

final_metrics_df[final_metrics_df["total_gt"] > 0]

,key,precision,recall,f1-score,tp,total_gt,accuracy
0,menu.nm,0.710843,0.713710,0.712274,177,251,0.705179
1,menu.num,0.041475,0.818182,0.078947,9,11,0.818182
2,menu.unitprice,0.231092,0.820896,0.360656,55,67,0.820896
3,menu.cnt,0.719149,0.793427,0.754464,169,220,0.768182
4,menu.discountprice,0.017094,0.571429,0.033195,4,7,0.571429
5,menu.price,0.728745,0.737705,0.733198,180,246,0.731707
6,menu.itemsubtotal,0.012048,0.500000,0.023529,3,6,0.500000
8,menu.etc,0.000000,0.000000,0.000000,0,3,0.000000
9,menu.sub,0.000000,0.000000,0.000000,0,22,0.000000
16,sub_total.discount_price,0.051020,0.833333,0.096154,5,6,0.833333
17,sub_total.service_price,0.090909,0.750000,0.162162,9,12,0.750000
19,sub_total.tax_price,0.230000,0.534884,0.321678,23,43,0.534884
20,sub_total.etc,0.020408,0.285714,0.038095,2,7,0.285714
21,total.total_price,0.846939,0.873684,0.860104,83,95,0.873684
23,total.cashprice,0.591837,0.865672,0.703030,58,67,0.865672
24,total.changeprice,0.489796,0.857143,0.623377,48,56,0.857143
25,total.creditcardprice,0.122449,0.750000,0.210526,12,16,0.750000
26,total.emoneyprice,0.000000,0.000000,0.000000,0,1,0.000000
27,total.menutype_cnt,0.061224,0.857143,0.114286,6,7,0.857143
28,total.menuqty_cnt,0.183673,0.620690,0.283465,18,29,0.620690